In [13]:
import numpy
import matplotlib
ms=50.0         #unit kg weight of the rocket shell
g = 9.81      # gravity in m s^{-2}
p = 1.091       #average air density constant throughout flight in kg/m^3
r = 0.5
A=numpy.pi*(r**2)      #maxium cross sectional area of the rocket 
ve=325.0        #exhaust speed in m/s
Cd=0.15       #drag coefficient
mp0=100.0       #initial weight of the rocket propellant in kg
mpc=20.0        # mass flow rate in kg/s

#set initial conditions:
v0=0.0    #start at stationary condition
h0=0.0    #launch from the ground
t0=0.0     #initial launching time

def f(u):
    h=u[0]
    v=u[1]
    t=u[2]
    return numpy.array([v, 
                        -g+(mpc*ve)/(ms+mp)-p*v*numpy.abs(v)*A*Cd/(2*(ms+mp)), 
                        1])
T=20.0                #final time
dt=0.1                #time increment
N=int(T/dt)+1         #number of time-steps
#initialize the array containing the soluton for each time-step
u=numpy.empty((N, 3))
u[0]=numpy.array([h0, v0, t0])   #fill 1st element with initial values

def euler_step(u, f, dt):
    return u+dt*f(u)

    
    #time loop- Euler method
    for n in range(N-1):
        # while u[0,n]>=0:   
            
            if(n>=50):
                mp=0
                mpc=0
            else:
                mp=100-2*n
            u[n+1]= euler_step(u[n], f, dt)
print (u)

[[  0.00000000e+000   0.00000000e+000   0.00000000e+000]
 [  1.61660967e-316   1.12646967e-321   0.00000000e+000]
 [  2.97400229e+222   3.65280382e+233   5.06259293e+233]
 [  1.81909115e+217   6.03685735e-154   1.69264133e-139]
 [  1.39730307e-152   1.94902401e+227   6.87055487e+228]
 [  3.17045215e+180   1.56373722e-033   6.01347002e-154]
 [  1.07070510e+200   1.73789391e-152   5.14059057e+231]
 [  1.42560187e-071   1.69264133e-139   1.27709650e-152]
 [  1.06263405e+248   1.06399913e+248   1.30445674e+243]
 [  2.44141101e-152   2.46001415e+198   2.95850942e-061]
 [  1.57588671e-052   9.10016856e+276   1.44135281e-105]
 [  6.01347002e-154   1.75770063e-152   4.96042470e+180]
 [  1.69337696e-152   1.33856857e-152   1.99672860e+209]
 [  7.14585256e-062   6.01347037e-154   1.78081673e+195]
 [  4.26614651e+180   3.07059276e-080   8.54302485e-072]
 [  6.01347002e-154   3.62479951e+228   6.19180686e+223]
 [  1.48879086e-076   6.01347002e-154   9.76515890e+199]
 [  8.54516092e+194   3.1709585

In [5]:
h=u[:,0]
v=u[:,1]
t=u[:,2]

In [7]:
pyplot.figure(figsize=(9,7))
pyplot.grid(True)
pyplot.xlabel(r'x', fontsize=18)
pyplot.ylabel(r'y', fontsize=18)
pyplot.title('Rocket launch hight, fontsize=18 ')

NameError: name 'pyplot' is not defined

In [6]:
pyplot.plot(t,h, 'k-', lw=2)

NameError: name 'pyplot' is not defined

In [ ]:
""